name: Build

on:
  push:
    branches: [main, master, develop, solpp]
  pull_request:
    branches: [main, master, develop, solpp]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpp-matrix:
    runs-on: ubuntu-latest
    name: Generate Test Matrix
    outputs:
      matrix: ${{ steps.cpp-matrix.outputs.matrix }}
    steps:
      - name: Generate Test Matrix
        uses: alandefreitas/cpp-actions/cpp-matrix@master
        id: cpp-matrix
        with:
          standards: ">=17 <=20"
          compilers: |
            gcc >=8
            clang >=16
            msvc >=14
            apple-clang *
            mingw *
            clang-cl *
          subrange-policy: |
            foo: bar
            msvc: one-per-minor
          latest-factors: |
            gcc         UBSan Coverage Shared
            clang       UBSan ASan MSan Shared
            apple-clang UBSan ASan Shared
            msvc        DebugBuild RelWithDebInfoBuild Shared
          build-types: |
            msvc DebugBuild: Debug
            msvc RelWithDebInfoBuild: RelWithDebInfo
          factors: |
            gcc         lua51 lua52 lua53 lua54 luaJit
            clang       lua51 lua52 lua53 lua54 luaJit
            apple-clang lua51 lua52 lua53 lua54 luaJit
            msvc        lua51 lua52 lua53 lua54 luaJit
          extra-values: |
            lua-version: {{#if lua51}}5.1{{else if lua52}}5.2{{else if lua53}}5.3{{else if lua54}}5.4{{else if luaJit}}LuaJIT{{else}}5.5{{/if}}
          max-standards: 1
          trace-commands: true
  build:
    needs: cpp-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.cpp-matrix.outputs.matrix) }}

    # use matrix entries
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}

    steps:
      - name: Clone library
        uses: actions/checkout@v7

      - name: Setup C++ Compiler
        uses: alandefreitas/cpp-actions/setup-cpp@master
        id: setup-cpp
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Install packages
        uses: alandefreitas/cpp-actions/package-install@master
        id: package-install
        with:
          apt-get: ${{ matrix.install }}
          apt-get-ignore-missing: ${{ matrix.is-container }}
          cc: ${{ steps.setup-cpp.outputs.cc }}
          ccflags: ${{ matrix.ccflags }}
          cxx: ${{ steps.setup-cpp.outputs.cxx }}
          cxxflags: ${{ matrix.cxxflags }}

      - name: CMake Workflow
        uses: alandefreitas/cpp-actions/cmake-workflow@master
        with:
          cc: ${{ steps.setup-cpp.outputs.cc || matrix.cc }}
          cxx: ${{ steps.setup-cpp.outputs.cxx || matrix.cxx }}
          cxxstd: ${{ matrix.cxxstd }}
          cmake-version: ">=3.26"
          ccflags: ${{ matrix.ccflags }}
          cxxflags: ${{ matrix.cxxflags }}
          toolchain: ${{ steps.package-install.outputs.vcpkg_toolchain || steps.package-install.outputs.vcpkg-toolchain }}
          build-type: ${{ matrix.build-type }}
          # prettier-ignore
          extra-args: "\"-DSOL2_LUA_VERSION=${{ matrix.lua-version }}\" -DSOL2_CI=ON -DSOL2_BUILD_LUA=ON -DBUILD_LUA_AS_DLL=${{ matrix.shared && 'ON' || 'OFF'}} -DSOL2_TESTS=ON -DSOL2_EXAMPLES=${{ case(matrix.coverage || false, 'OFF', 'ON') }} -DSOL2_TESTS_EXAMPLES=ON"
          package: false
          install: false

      # This is mostly copied from the mrdocs CI
      - name: Codecov
        id: codecov
        if: matrix.coverage
        run: |
          set -euvx

          # Find gcov
          gcov_tool="gcov"
          for version in "${{steps.setup-cpp.outputs.version-major}}" "${{steps.setup-cpp.outputs.version-major}}.${{steps.setup-cpp.outputs.version-minor}}"; do
            if command -v "gcov-$version" &> /dev/null; then
              gcov_tool="gcov-$version"
              break
            fi
          done

          dir="./build"
          lcov --rc branch_coverage=0 --gcov-tool "$gcov_tool" --directory "$dir" --capture --output-file "$dir/all.info" --ignore-errors inconsistent,negative,missing,source
          lcov --rc branch_coverage=0 --ignore-errors inconsistent,negative,missing,source --list "$dir/all.info"
          echo "file=$(realpath "$dir/all.info")" >> $GITHUB_OUTPUT

      - name: Upload Coverage as Artifact
        if: matrix.coverage
        uses: actions/upload-artifact@v6
        with:
          name: Coverage
          path: ${{ steps.codecov.outputs.file }}

      - name: Codecov Upload
        uses: codecov/codecov-action@v7
        if: matrix.coverage
        with:
          fail_ci_if_error: true
          files: ${{ steps.codecov.outputs.file }}
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
