name: Build

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpp-matrix:
    runs-on: ubuntu-latest
    name: Generate Test Matrix
    outputs:
      matrix: ${{ steps.cpp-matrix.outputs.matrix }}
    steps:
      - name: Generate Test Matrix
        uses: alandefreitas/cpp-actions/cpp-matrix@master
        id: cpp-matrix
        with:
          standards: ">=17"
          compilers: |
            gcc >=8
            clang >=16
            msvc >=14
            apple-clang *
            mingw *
            clang-cl *
          subrange-policy: |
            foo: bar
            msvc: one-per-minor
          factors: "Shared"
          latest-factors: |
            msvc v142 v143 v144
          max-standards: 1
          trace-commands: true
  build:
    needs: cpp-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.cpp-matrix.outputs.matrix) }}

    # use matrix entries
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}

    steps:
      - name: Clone library
        uses: actions/checkout@v4

      - name: Setup C++ Compiler
        uses: alandefreitas/cpp-actions/setup-cpp@master
        id: setup-cpp
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Install packages
        uses: alandefreitas/cpp-actions/package-install@master
        id: package-install
        with:
          apt-get: ${{ matrix.install }}
          apt-get-ignore-missing: ${{ matrix.is-container }}
          cc: ${{ steps.setup-cpp.outputs.cc }}
          ccflags: ${{ matrix.ccflags }}
          cxx: ${{ steps.setup-cpp.outputs.cxx }}
          cxxflags: ${{ matrix.cxxflags }}

      - name: CMake Workflow
        uses: alandefreitas/cpp-actions/cmake-workflow@master
        with:
          cc: ${{ steps.setup-cpp.outputs.cc || matrix.cc }}
          cxx: ${{ steps.setup-cpp.outputs.cxx || matrix.cxx }}
          cxxstd: ${{ matrix.cxxstd }}
          cmake-version: ">=3.26"
          # prettier-ignore
          extra-args: "\"-DSOL2_LUA_VERSION=5.4\" -DSOL2_PLATFORM=x64 -DSOL2_CI=ON -DSOL2_BUILD_LUA=ON -DBUILD_LUA_AS_DLL=${{ matrix.shared && 'ON' || 'OFF'}} -DSOL2_TESTS=ON -DSOL2_EXAMPLES=ON -DSOL2_TESTS_EXAMPLES=ON"
          package: false
          build-type: Debug
          install: false
          generator-toolset: ${{ matrix.v142 && 'v142' || (matrix.v143 && 'v143' || (matrix.v144 && 'v144' || '')) }}
